[general]
import = ["~/.config/alacritty/theme/catppuccin-frappe.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 5
decorations = "buttonless"
option_as_alt = "Both"

[font]
normal.family = "Operator Mono"
normal.style = "Book"
bold.style = "Medium"
size = 16
offset.y = 10

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
